const std = @import("std");
const Timestamp = std.Io.Timestamp;

const root = @import("../../root.zig");
const random = root.util.random;
const Uuid = root.util.Uuid;

/// UUIDv7 features a time-ordered value field derived from the widely implemented and well-known
/// Unix Epoch timestamp source, the number of milliseconds since midnight 1 Jan 1970 UTC, leap
/// seconds excluded.
///
/// This ID is **NOT** strictly monotonically increasing, but it is generally increasing with time.
/// It is suggested to be used as the key in a database since in most databases, the default index
/// is a B-tree, which is more efficient when the keys are generally increasing.
///
/// Generally, UUIDv7 has improved entropy characteristics over UUIDv1 or UUIDv6, Implementations
/// **SHOULD** utilize UUIDv7 instead of UUIDv1 and UUIDv6 if possible.
///
/// https://www.rfc-editor.org/info/rfc9562/#section-5.7
pub const V7 = packed struct {
    /// big-endian unsigned number of the Unix Epoch timestamp in milliseconds
    unix_ts_ms: u48,
    ver: Uuid.Version = .v7,
    rand_a: u12,
    variant: u2 = Uuid.VARIANT,
    rand_b: u62,

    pub const Error = error{
        /// The timestamp is a negative value or exceeds the maximum representable value of 48 bits.
        /// This might occur if the service is running on a virtual machine with an incorrect clock.
        TimestampOverflow,
    };

    /// `rand_src` will use `std.Io.randomSecure` if possible.
    /// The unix timestamp will be generated by the Io inside `rand_src`.
    ///
    /// Implementations SHOULD utilize a cryptographically secure pseudorandom number generator to
    /// provide values that are both difficult to predict ("unguessable") and have a low likelihood
    /// of collision ("unique").
    ///
    /// https://www.rfc-editor.org/info/rfc9562/#name-unguessability
    ///
    /// ### Fallback suggestion
    /// - `Uuid.V4.init` if `Error`.
    pub fn init(rand_src: random.IoSourceSecure) Error!@This() {
        return try initImpl(std.Io.Clock.real.now(rand_src.io), rand_src.interface());
    }

    /// Faster than `init` but less secure. Use only if you have a good reason to do so.
    pub fn initInsecure(rand_src: random.IoSource) Error!@This() {
        return try initImpl(std.Io.Clock.real.now(rand_src.io), rand_src.interface());
    }

    pub fn initImpl(unix_ts: Timestamp, rand: std.Random) Error!@This() {
        const unix_ts_ms = unix_ts.toMilliseconds();
        if (unix_ts_ms < 0 or unix_ts_ms > std.math.maxInt(u48)) {
            return Error.TimestampOverflow;
        }
        return .{
            .unix_ts_ms = @intCast(unix_ts_ms),
            .rand_a = rand.int(u12),
            .rand_b = rand.int(u62),
        };
    }

    pub fn toUuid(self: @This()) root.util.Uuid {
        return .{
            .sec_a = self.unix_ts_ms,
            .ver = self.ver,
            .sec_b = self.rand_a,
            .variant = self.variant,
            .sec_c = self.rand_b,
        };
    }

    pub fn toU128(self: @This()) u128 {
        return @bitCast(self);
    }

    pub fn toString(self: @This()) [16]u8 {
        return @bitCast(self);
    }
};

const expect = std.testing.expect;
const expectError = std.testing.expectError;
const expectEqual = std.testing.expectEqual;

test "call init with Io" {
    const io = std.testing.io;
    _ = try V7.init(.{ .io = io });
    _ = try V7.initInsecure(.{ .io = io });
}

test "initImpl returns TimestampOverflow for invalid timestamp" {
    const negative_ts = Timestamp.fromNanoseconds(-1 * std.time.ns_per_ms);
    const overflow_ts = Timestamp.fromNanoseconds((std.math.maxInt(u48) + 1) * std.time.ns_per_ms);

    var mock_source = random.MockSource{
        .buffers = &.{ &[_]u8{0} ** 2, &[_]u8{0} ** 8 },
    };
    const mock = mock_source.interface();

    try expectError(V7.Error.TimestampOverflow, V7.initImpl(negative_ts, mock));
    try expectError(V7.Error.TimestampOverflow, V7.initImpl(overflow_ts, mock));
}

test "initImpl timestamp edge condition" {
    var mock_max_source = random.MockSource{
        .buffers = &.{ &[_]u8{0xFF} ** 2, &[_]u8{0xFF} ** 8 },
    };
    const max_valid_ts = Timestamp.fromNanoseconds(std.math.maxInt(u48) * std.time.ns_per_ms);
    const mock_max = mock_max_source.interface();
    const uuid_max = try V7.initImpl(max_valid_ts, mock_max);

    var mock_zero_source = random.MockSource{
        .buffers = &.{ &[_]u8{0} ** 2, &[_]u8{0} ** 8 },
    };
    const mock_zero = mock_zero_source.interface();
    const uuid_zero = try V7.initImpl(Timestamp.zero, mock_zero);

    try expectEqual(uuid_max.unix_ts_ms, std.math.maxInt(u48));
    try expectEqual(uuid_max.rand_a, std.math.maxInt(u12));
    try expectEqual(uuid_max.rand_b, std.math.maxInt(u62));
    try expectEqual(uuid_zero.unix_ts_ms, 0);
    try expectEqual(uuid_zero.rand_a, 0);
    try expectEqual(uuid_zero.rand_b, 0);
}

test "Uuid v7 additional monotonicity by milliseconds" {
    var mock_source = random.MockSource{
        .buffers = &.{ &[_]u8{0} ** 2, &[_]u8{0} ** 8 },
    };
    const mock = mock_source.interface();

    const uuid1 = try V7.initImpl(Timestamp.fromNanoseconds(std.time.ns_per_ms), mock);
    const uuid2 = try V7.initImpl(Timestamp.fromNanoseconds(2 * std.time.ns_per_ms), mock);
    try expect(uuid1.toU128() < uuid2.toU128());
}

test "type transfer consistency" {
    var mock_source = random.MockSource{
        .buffers = &.{ &[_]u8{0x12} ** 2, &[_]u8{0x34} ** 8 },
    };
    const mock = mock_source.interface();
    const uuid = try V7.initImpl(Timestamp.fromNanoseconds(std.time.ns_per_ms), mock);

    const uuid_as_layout = uuid.toUuid();
    const uuid_as_u128 = uuid.toU128();
    const uuid_as_str = uuid.toString();

    const uuid_from_layout: V7 = @bitCast(uuid_as_layout);
    const uuid_from_u128: V7 = @bitCast(uuid_as_u128);
    const uuid_from_bytes: V7 = @bitCast(uuid_as_str);

    try expectEqual(uuid, uuid_from_layout);
    try expectEqual(uuid, uuid_from_u128);
    try expectEqual(uuid, uuid_from_bytes);
}
